replicaCount: 3
image:
  repository: nginx
  tag: 1.27.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 0.5
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 50Mi

nameOverride: ""
fullnameOverride: ""

labels:
  app: mht-nginx-app
  deployment: mht-nginx-deployment
  container: mht-nginx-container
