replicaCount: 2

image:
  repository: nginx
  tag: 1.27.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 0.5
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 50Mi

nameOverride: ""
fullnameOverride: ""

labels:
  app: mht-golang-app
  deployment: mht-golang-deployment
  container: mht-golang-container
